# These are supported funding model platforms
# GitHub will show a "Sponsor" button linking to these

# Native platforms (uncomment when accounts are set up)
# github: myProjectsRavi
# patreon: username

# Custom links — Replace the URLs below with your actual Lemon Squeezy + PayPal links
custom:
  - https://paypal.me/rtnlabs
  - https://rtnlabs.lemonsqueezy.com/checkout/buy/1a38a624-8fd5-4308-bb41-d2934c12051d
