# These are supported funding model platforms
# GitHub will show a "Sponsor" button linking to these

# Native platforms (uncomment when accounts are set up)
# github: myProjectsRavi
# patreon: username

# Custom links — Replace the URLs below with your actual Lemon Squeezy + PayPal links
custom:
  - https://www.paypal.me/YOUR_PAYPAL_USERNAME
